# Generated by Django 5.1.1 on 2024-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_useradmin_delete_productredactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='username',
            new_name='usersss',
        ),
    ]
