# Generated by Django 5.1.1 on 2024-10-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_rename_username_useradmin_usersss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='usersss',
            new_name='username',
        ),
    ]
