# Generated by Django 5.1.1 on 2024-11-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_useradmin_username'),
        ('main', '0009_alter_orders_method_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdmin',
            new_name='ProductRedactor',
        ),
        migrations.RemoveField(
            model_name='productredactor',
            name='username',
        ),
        migrations.AddField(
            model_name='productredactor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
