# Generated by Django 5.1.1 on 2024-10-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof1le',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='')),
                ('contacts', models.CharField(max_length=19)),
                ('order_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
