# Generated by Django 5.1.1 on 2024-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prof1le_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof1le',
            name='contacts',
        ),
    ]
