# Generated by Django 5.1.1 on 2024-10-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_prof1le_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='methods',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('contacts', models.CharField(max_length=19)),
                ('method', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AlterField(
            model_name='prof1le',
            name='order_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
